### PR TITLE
Add support for QNX Neutrino

### PR DESCRIPTION
**Pull request by flba-eb**
See also https://github.com/rust-lang/rust/blob/57c215b08e18054c64428e00a291b45dc690d9de/library/std/src/sys/unix/os.rs#L64

### CODE REVIEW

**Comment by lambda-fairy** [comment]
Thanks for the PR!

Can you please add an entry to the [changelog](https://github.com/lambda-fairy/rust-errno/blob/main/CHANGELOG.md) as well?

**Comment by flba-eb** [comment]
I've added a note to the [Unreleased] section; I can also move it to [0.3.2] if you release it today (or provide the release date).

**Comment by flba-eb** [comment]
Message of failing CI:
> info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: update not yet available, sorry! try again later
error: toolchain 'nightly-x86_64-apple-darwin' is not installable
Error: Process completed with exit code 1.

I guess this is not related to my changes.

**Comment by lambda-fairy** [comment]
LGTM, thanks!

> I can also move it to [0.3.2] if you release it today (or provide the release date).

I'll do that when I cut the release.

**Pull request merged**
